### PR TITLE
fix: Update .travis.yml for travis-ci.com

### PR DESCRIPTION
**Pull request by riddell-stan**

### CODE REVIEW

**Comment by riddell-stan** [comment]
This is incomplete. It needs some additional logic about uploading wheels if the commit is tagged. Or we might simply try to upload to pypi on every commit using the ``--skip-existing`` flag.

**Comment by riddell-stan** [comment]
I believe we can check if we are on the master branch (vs. a pull request). If we are on the master branch, we can upload the wheel with --skip-existing.

**Comment by ahartikainen** [comment]
Yes, I think we can do it like that

**Comment by riddell-stan** [comment]
The macOS builds fail but that's to be expected. The macOS problems will be fixed in the next version of httpstan.

**Pull request merged**
